### ISSUE TITLE
ProjectRed ores spawning

### ISSUE THREAD

**Issue by xMisterTurtle** [pahimar/ForgeCraftTheModpack#1]
You forgot to turn off PR ore gen in configs. Silly Pahimar

**Comment by pahimar** [comment]
It wasn't forgotten

**Comment by Mrdlor** [comment]
I'm sorry to open this up again but i just want to make sure everyone understands each other.
By ''it wasn't forgotten'' you mean it was left on , on purpose Pahimar?
Or you mean that it's not on? 
Because it is: http://i.imgur.com/6LrmDMO.png

Just making sure :)

**Comment by pahimar** [comment]
The ore gen is on on purpose
